### ISSUE TITLE
Build error in master

### ISSUE THREAD

**Issue by awnixon** [spring-guides/gs-spring-boot-docker#43]
Hello, 

I'm attempting to build the complete project 'gs-spring-boot-docker-master/complete'.
Issuing the command `mvn clean package docker:build` results in the following:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3.714s
> [INFO] Finished at: Thu Feb 08 18:15:50 GMT 2018
> [INFO] Final Memory: 19M/46M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project gs-spring-boot-docker: Exception caught: Must specify baseImage if dockerDirectory is null -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project gs-spring-boot-docker: Exception caught
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
> Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
>         at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:151)
>         at com.spotify.docker.BuildMojo.execute(BuildMojo.java:87)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
>         ... 19 more
> Caused by: org.apache.maven.plugin.MojoExecutionException: Must specify baseImage if dockerDirectory is null
>         at com.spotify.docker.BuildMojo.validateParameters(BuildMojo.java:549)
>         at com.spotify.docker.BuildMojo.execute(BuildMojo.java:331)
>         at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:149)
>         ... 22 more
> [ERROR]
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> 

No changes have been made to the project since downloading.
A previous error:
>  No plugin found for prefix 'docker' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo]
was resolved by adding the following to my maven settings.xml
>  <pluginGroups>
>    <pluginGroup>com.spotify</pluginGroup>
>  </pluginGroups>

I'm unable to make any further progress in resolving this error.

**Comment by awnixon** [comment]
The issue was simple - the command is `mvn clean package dockerfile:build` and not `mvn clean package docker:build`
