### ISSUE TITLE
Dockerbuild not possible due to JsonMappingException

### ISSUE THREAD

**Issue by badping** [spring-guides/gs-spring-boot-docker#63]
How to reproduce:
1) Install: Docker for Windows: Version 2.0.0.0-win81 (29211) on Windows 10 Pro
2) Checkout the complete spring boot docker repo
3) Execute the dockerfile build: ./mvnw install dockerfile:build

Anyone an idea whats wrong here, i really have no changes in the git repo, just cloned it and executed it.

See my maven trace:
> [INFO] --- dockerfile-maven-plugin:1.3.6:build (default-cli) @ gs-spring-boot-docker ---
[INFO] Building Docker context C:\Projects\gs-spring-boot-docker\complete
[INFO]
[INFO] Image will be built as springio/gs-spring-boot-docker:latest
[INFO]
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:185)
        at com.spotify.plugin.dockerfile.BuildMojo.execute(BuildMojo.java:105)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.tryExecute(AbstractDockerMojo.java:240)
        at com.spotify.plugin.dockerfile.AbstractDockerMojo.execute(AbstractDockerMojo.java:229)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: com.spotify.docker.client.exceptions.DockerException: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.RegistryAuth: no String-argument constructor/factory method to deserialize from String value ('swarm')
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.LinkedHashMap["stackOrchestrator"])
        at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:102)
        at com.spotify.docker.client.auth.MultiRegistryAuthSupplier.authForBuild(MultiRegistryAuthSupplier.java:77)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1388)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1365)
        at com.spotify.plugin.dockerfile.BuildMojo.buildImage(BuildMojo.java:178)
        ... 32 more
Caused by: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.spotify.docker.client.messages.RegistryAuth: no String-argument constructor/factory method to deserialize from String value ('swarm')
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.LinkedHashMap["stackOrchestrator"])
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:315)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1283)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:159)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:517)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1187)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3770)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2099)
        at com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2596)
        at com.spotify.docker.client.DockerConfigReader.parseDockerConfig(DockerConfigReader.java:95)
        at com.spotify.docker.client.DockerConfigReader.fromConfig(DockerConfigReader.java:48)
        at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:100)
        ... 36 more

**Comment by gregturn** [comment]
Switch to your own docker hub .org.

**Comment by badping** [comment]
Is there a short description how i can do that ? I didnt see this step in the tutorial. 
Best regards! 


Von: "Greg Turnquist" <notifications@github.com> 
An: "spring-guides/gs-spring-boot-docker" <gs-spring-boot-docker@noreply.github.com> 
CC: "Johannes Lechner" <Johannes.Lechner@consol.de>, "Author" <author@noreply.github.com> 
Gesendet: Donnerstag, 13. Dezember 2018 14:08:09 
Betreff: Re: [spring-guides/gs-spring-boot-docker] Dockerbuild not possible due to JsonMappingException (#63) 



Switch to your own docker hub .org.

**Comment by gregturn** [comment]
Read the part of the guide about pushing your docker image. It clearly cites changing this fact.

**Comment by badping** [comment]
I am a bit confused because i just want to build the image with maven not pushing it. 
In addition if i build it with gradle it works fine without any change (out of the box). 
Best regards. 


Von: "Greg Turnquist" <notifications@github.com> 
An: "spring-guides" <gs-spring-boot-docker@noreply.github.com> 
CC: "Johannes Lechner" <Johannes.Lechner@consol.de>, "Author" <author@noreply.github.com> 
Gesendet: Donnerstag, 13. Dezember 2018 14:43:12 
Betreff: Re: [spring-guides/gs-spring-boot-docker] Dockerbuild not possible due to JsonMappingException (#63) 



Read the part of the guide about pushing your docker image. It clearly cites changing this fact.

**Comment by dsyer** [comment]
It looks like maybe you have to authenticate with dockerhub if you use that form of image name. You could change it to something else to pick a different authentication strategy (I think that's the way docker works). Or just authenticate with `docker login`. If that works, then I agree it is probably a bug in the Maven plugin.

**Comment by badping** [comment]
I found a workaround solution. 
I logged in with docker-ID then i received during the build a new error: 
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect 
To fix this i had to activate General -> "Expose daemon on tcp://localhost:2375 without TLS 

But docker says this legacy export should not be used as it enables remote execution attacks. 

At least it is a workaround, but not the perfect solution. 
Maybe someone has a better solution for it. 

Best regards. 



Von: "Dave Syer" <notifications@github.com> 
An: "spring-guides" <gs-spring-boot-docker@noreply.github.com> 
CC: "Johannes Lechner" <Johannes.Lechner@consol.de>, "Author" <author@noreply.github.com> 
Gesendet: Donnerstag, 13. Dezember 2018 15:36:26 
Betreff: Re: [spring-guides/gs-spring-boot-docker] Dockerbuild not possible due to JsonMappingException (#63) 



It looks like maybe you have to authenticate with dockerhub if you use that form of image name. You could change it to something else to pick a different authentication strategy (I think that's the way docker works). Or just authenticate with docker login . If that works, then I agree it is probably a bug in the Maven plugin.

**Comment by badping** [comment]
Just one more point here, i suggest to update the maven dockerfile plugin to v1.4.9. 
With this new version i directly got the localhost connect issue and the first issue didnt occur for me. 
Best regards. 


Von: "Dave Syer" <notifications@github.com> 
An: "spring-guides" <gs-spring-boot-docker@noreply.github.com> 
CC: "Johannes Lechner" <Johannes.Lechner@consol.de>, "Author" <author@noreply.github.com> 
Gesendet: Donnerstag, 13. Dezember 2018 15:36:26 
Betreff: Re: [spring-guides/gs-spring-boot-docker] Dockerbuild not possible due to JsonMappingException (#63) 



It looks like maybe you have to authenticate with dockerhub if you use that form of image name. You could change it to something else to pick a different authentication strategy (I think that's the way docker works). Or just authenticate with docker login . If that works, then I agree it is probably a bug in the Maven plugin.

**Comment by dsyer** [comment]
Everything works for me when I am authenticated. If we need to clarify something, please suggest what is missing.
